Add segmentation pipeline widget
ssciwr/adaptivefiltering pull request #198
Opened 2022-02-23 14:36 UTC by GwydionJon

This solves #139

2022-02-23 16:49 UTC, dokempf commented
The failing test is a change to a notebook that should not have been part of the PR in the first place.

2022-02-24 20:02 UTC, dokempf requested changes
I added some review comments. They mostly refer either to style or the change of user facing APIs. Once that is fixed, we need to do a second iteration of the feature after my discussion with Bernhard today.

2022-02-24 20:02 UTC, dokempf commented on adaptivefiltering/segmentation.py
> +    def convert(self, srs_in, srs_out="EPSG:4326"):
Having this as a user facing API suggests that there is a use case where a user needs this. When would that be?

2022-02-24 20:02 UTC, dokempf commented on adaptivefiltering/segmentation.py
> +        if override == True:
For booleans, just do `if override:`

2022-02-25 12:52 UTC, GwydionJon commented on adaptivefiltering/apps.py
> +from ipyleaflet import Marker
Marker is no longer needed anyway.

2022-02-25 12:59 UTC, GwydionJon commented on adaptivefiltering/dataset.py
> +    def assign_pipeline(self, segmentation, pipelines):
My thinking was that this makes it easier to associate the operation with the given dataset.

2022-02-25 13:12 UTC, dokempf commented on adaptivefiltering/segmentation.py
> +    def convert(self, srs_in, srs_out="EPSG:4326"):
Okay, so we remove that.

2022-02-25 13:13 UTC, dokempf commented on adaptivefiltering/dataset.py
> +    def assign_pipeline(self, segmentation, pipelines):
I think I would rather not add more things to DataSet.

2022-02-25 13:50 UTC, merged