Beautify adaptfilter show
ssciwr/adaptivefiltering pull request #20
Opened 2021-06-28 11:19 UTC by GwydionJon

#18 
Changed axis to have Z facing upwards, removed box and added variable threshold with prior warning.

2021-06-28 18:15 UTC, dokempf commented
The problem is that we do version pinning in `setup.py`: https://github.com/ssciwr/adaptivefiltering/blob/main/setup.py#L13 Removing that constraint should enable installation of version 2 and solve the problem.

2021-06-30 11:57 UTC, GwydionJon commented
With the new laspy version the ipyvolume scatter function throws an index error, when directly using self.data.x for the input. Converting this ScaledArrayView object into a numpy array fixes the error and plots the scatter. 
This workaround seems undesirable.

2021-06-30 12:03 UTC, dokempf commented
If `laspy` changed their format, we should definitely adapt to it.

2021-06-30 13:15 UTC, dokempf commented
For obscure reasons, any changes to `environment.yml` need to be duplicated in `doc/environment-rtd.yml` with a version pin applied. Otherwise, the RTD build runs out of memory in solving the conda environment.

2021-07-01 14:35 UTC, dokempf requested changes
Apart from my comment about old code, this is ready to be merged.

2021-07-01 14:35 UTC, dokempf commented on adaptivefiltering/dataset.py
> +        # old laspy style
I would prefer outdated code to be removed from the repository. We will not move back to `laspy<2`.

2021-07-02 12:41 UTC, merged